"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Aladin, Playfair_Display, Lilita_One } from 'next/font/google'
import { AuthContextProvider } from '@/context/AuthContext'

const inter = Inter({ subsets: ['latin'] })
export const lilita = Lilita_One({
  subsets: ['latin'],
  weight: ['400']
})
export const aladin = Aladin({
  subsets: ["latin"],
  weight: ['400']
})
export const playfair = Playfair_Display({
  subsets: ['latin'],
  style: ['italic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lilita.className}`}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
